### ISSUE TITLE
编译 error

### ISSUE THREAD

**Issue by iHTCboy** [JeansHuang/Potatso#1]
执行 carthage update后，还是报了3个错误：

clang: error: no such file or directory: '/Users/HTC/Documents/Programing/iGitHub/Potatso/Library/ShadowPath/ShadowPath/shadowsocks-libev/libipset/set/inspection.c'
clang: error: no input files

clang: error: no such file or directory: '/Users/HTC/Documents/Programing/iGitHub/Potatso/Library/ShadowPath/ShadowPath/shadowsocks-libev/libcork/core/timestamp.c'
clang: error: no input files

clang: error: no such file or directory: '/Users/HTC/Documents/Programing/iGitHub/Potatso/Library/ShadowPath/ShadowPath/shadowsocks-libev/src/tls1.2_ticket.c'
clang: error: no input files

**Comment by JeansHuang** [comment]
你是执行  `git clone --recursive https://github.com/JeansHuang/Potatso.git`  clone项目的吗？

**Comment by JeansHuang** [comment]
clone 要加  `--recursive`

**Comment by iHTCboy** [comment]
是啊：

git clone --recursive https://github.com/JeansHuang/Potatso.git
carthage update

根据你的来加了，是不是要更新carthage 版本，我是用Xcode 9.2 的。

**Comment by alsojin0806** [comment]
我的Xcode 9.2  可以编译成功 但是直接闪退

**Comment by JeansHuang** [comment]
你这报错就是没clone到ShadowPath，git clone --recursive 都clone完整的话，应该没问题。刚试了可以。我目前用的也是Xcode 9.2 (9C40b)。要不换SourceTree  clone试试，勾选上 Recurse submodules

**Comment by alsojin0806** [comment]
能正常运行了 但是不能添加配置 啊

**Comment by iHTCboy** [comment]
@JeansHuang  好的，SourceTree clone试试，勾选上 Recurse submodules，这个我晚点试试！Thanks!

**Comment by azhm** [comment]
你好 我勾选了 Recurse submodules 
我也尝试了 git clone --recursive https://github.com/JeansHuang/Potatso.git
但是clone下了的 shadowsocks-libev总是空的。。。。 请问是什么情况呢

**Comment by azhm** [comment]
权限问题

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:phimage/CallbackURLKit.git' into submodule path '/Users/leon/cs/Potatso/Library/CallbackURLKit' failed
Failed to clone 'Library/CallbackURLKit'. Retry scheduled
Cloning into '/Users/leon/cs/Potatso/Library/Eureka'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by JeansHuang** [comment]
已经更新支持Xcode9.3了，重新clone即可
