### ISSUE TITLE
编译报错 No member named 're_erroffset' in 'regex_t'

### ISSUE THREAD

**Issue by azhm** [JeansHuang/Potatso#2]
<img width="1176" alt="wx20180328-161051 2x" src="https://user-images.githubusercontent.com/12508146/38016792-b446972c-32a2-11e8-90d7-0210c03e93a2.png">

addlength = (preg != NULL && (int)preg->re_erroffset != -1)?
No member named 're_erroffset' in 'regex_t'
你好 我这边编译了好几个版本 最后都是出现这个错误 网上也查不到资料
麻烦解答一下 感谢🙏

**Comment by JeansHuang** [comment]
那就装个旧点的Xcode咯

**Comment by JeansHuang** [comment]
已经更新支持Xcode9.3了，重新clone即可

**Comment by azhm** [comment]
好的 我再試試 感謝
